objects/Child__c/Child__c.object-meta.xml
<CustomObject>
    <label>자녀</label>
    <nameField>
        <label>자녀 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Child__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>통화</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Child__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>롤업 요약로 가장 최근 날짜를 습득하기 위한 레코드</description>
    <label>날짜</label>
    <type>Date</type>
</CustomField>

objects/Child__c/fields/Decimal__c.field-meta.xml
<CustomField>
    <fullName>Decimal__c</fullName>
    <label>숫자</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Child__c/fields/Parents__c.field-meta.xml
<CustomField>
    <fullName>Parents__c</fullName>
    <label>부모</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>자녀</relationshipLabel>
    <relationshipName>Child_Parents_Rel</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <description>개체 레코드 타입에 따른 사용 방법(부모)</description>
    <label>부모</label>
    <nameField>
        <label>부모 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Parent__c/fields/AutoNumber__c.field-meta.xml
<CustomField>
    <fullName>AutoNumber__c</fullName>
    <displayFormat>{00000000}</displayFormat>
    <label>자동 번호</label>
    <type>AutoNumber</type>
</CustomField>

objects/Parent__c/fields/Boolean__c.field-meta.xml
<CustomField>
    <fullName>Boolean__c</fullName>
    <defaultValue>false</defaultValue>
    <label>확인란</label>
    <type>Checkbox</type>
</CustomField>

objects/Parent__c/fields/BooleanFomula__c.field-meta.xml
<CustomField>
    <fullName>BooleanFomula__c</fullName>
    <formula>MaxDecimal__c &gt; 10</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>수식확인란</label>
    <type>Checkbox</type>
</CustomField>

objects/Parent__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>통화</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Parent__c/fields/CurrencyFomula__c.field-meta.xml
<CustomField>
    <fullName>CurrencyFomula__c</fullName>
    <formula>MaxCurrency__c - MinCurrency__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>수식통화</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Parent__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>날짜</label>
    <type>Date</type>
</CustomField>

objects/Parent__c/fields/DateFomula__c.field-meta.xml
<CustomField>
    <fullName>DateFomula__c</fullName>
    <formula>LastestDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>수식날짜</label>
    <type>Date</type>
</CustomField>

objects/Parent__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <label>날짜/시간</label>
    <type>DateTime</type>
</CustomField>

objects/Parent__c/fields/Decimal__c.field-meta.xml
<CustomField>
    <fullName>Decimal__c</fullName>
    <label>숫자</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Parent__c/fields/DecimalFomula__c.field-meta.xml
<CustomField>
    <fullName>DecimalFomula__c</fullName>
    <formula>MaxDecimal__c - MinDecimal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>수식숫자</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

objects/Parent__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>이메일</label>
    <type>Email</type>
</CustomField>

objects/Parent__c/fields/LastestDate__c.field-meta.xml
<CustomField>
    <fullName>LastestDate__c</fullName>
    <label>최근날짜</label>
    <summarizedField>Child__c.Date__c</summarizedField>
    <summaryForeignKey>Child__c.Parents__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Parent__c/fields/LongTextArea__c.field-meta.xml
<CustomField>
    <fullName>LongTextArea__c</fullName>
    <label>긴 텍스트 영역</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

objects/Parent__c/fields/MaxCurrency__c.field-meta.xml
<CustomField>
    <fullName>MaxCurrency__c</fullName>
    <label>통화최대값</label>
    <summarizedField>Child__c.Currency__c</summarizedField>
    <summaryForeignKey>Child__c.Parents__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Parent__c/fields/MaxDecimal__c.field-meta.xml
<CustomField>
    <fullName>MaxDecimal__c</fullName>
    <label>숫자최대값</label>
    <summarizedField>Child__c.Decimal__c</summarizedField>
    <summaryForeignKey>Child__c.Parents__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Parent__c/fields/MinCurrency__c.field-meta.xml
<CustomField>
    <fullName>MinCurrency__c</fullName>
    <label>통화최소값</label>
    <summarizedField>Child__c.Currency__c</summarizedField>
    <summaryForeignKey>Child__c.Parents__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Parent__c/fields/MinDecimal__c.field-meta.xml
<CustomField>
    <fullName>MinDecimal__c</fullName>
    <label>숫자최소값</label>
    <summarizedField>Child__c.Decimal__c</summarizedField>
    <summaryForeignKey>Child__c.Parents__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Parent__c/fields/OldestDate__c.field-meta.xml
<CustomField>
    <fullName>OldestDate__c</fullName>
    <label>오래된날짜</label>
    <summarizedField>Child__c.Date__c</summarizedField>
    <summaryForeignKey>Child__c.Parents__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Parent__c/fields/Parents__c.field-meta.xml
<CustomField>
    <fullName>Parents__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>부모</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>부모</relationshipLabel>
    <relationshipName>Parent_Parent_Rel</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Parent__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>백분율</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/Parent__c/fields/PercentFomula__c.field-meta.xml
<CustomField>
    <fullName>PercentFomula__c</fullName>
    <formula>Percent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>수식백분율</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/Parent__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>전화</label>
    <type>Phone</type>
</CustomField>

objects/Parent__c/fields/SelectList__c.field-meta.xml
<CustomField>
    <fullName>SelectList__c</fullName>
    <label>선택 목록</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Parent__c/fields/SelectListMultiple__c.field-meta.xml
<CustomField>
    <fullName>SelectListMultiple__c</fullName>
    <label>선택 목록 다중 선택</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Parent__c/fields/SumCurrency__c.field-meta.xml
<CustomField>
    <fullName>SumCurrency__c</fullName>
    <label>통화합계</label>
    <summarizedField>Child__c.Currency__c</summarizedField>
    <summaryForeignKey>Child__c.Parents__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Parent__c/fields/SumDecimal__c.field-meta.xml
<CustomField>
    <fullName>SumDecimal__c</fullName>
    <label>숫자합계</label>
    <summarizedField>Child__c.Decimal__c</summarizedField>
    <summaryForeignKey>Child__c.Parents__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/Parent__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>텍스트</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Parent__c/fields/TextArea__c.field-meta.xml
<CustomField>
    <fullName>TextArea__c</fullName>
    <label>텍스트 영역</label>
    <type>TextArea</type>
</CustomField>

objects/Parent__c/fields/TextEncryption__c.field-meta.xml
<CustomField>
    <fullName>TextEncryption__c</fullName>
    <label>텍스트암호화</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

objects/Parent__c/fields/TextFomula__c.field-meta.xml
<CustomField>
    <fullName>TextFomula__c</fullName>
    <formula>Text__c &amp; TextArea__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>수식텍스트</label>
    <type>Text</type>
</CustomField>

objects/Parent__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>시간</label>
    <type>Time</type>
</CustomField>

objects/Parent__c/fields/TimeFomula__c.field-meta.xml
<CustomField>
    <fullName>TimeFomula__c</fullName>
    <formula>Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>수식시간</label>
    <type>Time</type>
</CustomField>

objects/Parent__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>URL</label>
    <type>Url</type>
</CustomField>

classes/CntrlDspDataType.cls
/**
 * @description 레코드의 데이터 타입 표시 테스트용 화면 컨트롤러
 */
public with sharing class CntrlDspDataType {

    /**
     * @description 부모 레코드(화면 표시용)
     */
    public Parent__c parents { get; set; }

    /**
     * @description 자식 레코드(화면 표시용)
     */
    public List<Child__c> childList { get; set; }

    /**
     * @description 생성자
     */
    public CntrlDspDataType(ApexPages.StandardController stdController) {

        // 화면 표시용 부모 레코드 습득(가장 마지막에 등록한 레코드)
        parents = getParents();

        // 화면 표시용 자식 레코드 습득
        childList = getChildList();
    }

    /**
     * @description 부모 레코드 습득
     */
    private Parent__c getParents() {

        List<Parent__c> parentsList = [
            SELECT
                Id,
                Url__c,
                LongTextArea__c,
                Date__c,
                Datetime__c,
                Percent__c,
                Parents__c,
                Parents__r.Text__c,
                SelectList__c,
                SelectListMultiple__c,
                DateFomula__c,
                PercentFomula__c,
                DecimalFomula__c,
                TimeFomula__c,
                TextFomula__c,
                CurrencyFomula__c,
                BooleanFomula__c,
                Decimal__c,
                MaxDecimal__c,
                MinDecimal__c,
                SumDecimal__c,
                Time__c,
                OldestDate__c,
                Email__c,
                AutoNumber__c,
                Phone__c,
                LastestDate__c,
                Text__c,
                TextEncryption__c,
                TextArea__c,
                Currency__c,
                MaxCurrency__c,
                MinCurrency__c,
                SumCurrency__c,
                Boolean__c
            FROM
                Parent__c
            ORDER BY
                CreatedDate Desc
        ];

        return parentsList.get(0);
    }

    /**
     * @description 자식 레코드 습득
     */
    private List<Child__c> getChildList() {

        List<Child__c> childList = [
            SELECT
                Id,
                Date__c,
                Parents__c,
                Decimal__c,
                Currency__c
            FROM
                Child__c
        ];

        return childList;
    }
}